In [13]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import json
from pandas.io.json import json_normalize

# Import API key
#from config import api_keys

api_key= "8c8bdba55a6a45865a43f90bdfbfabb7"
url = "http://api.openweathermap.org/data/2.5/weather?"

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

In [14]:
# List for holding lat_lngs and cities
lat_lngs = []
cities = []


# Create a set of random lat and lng combinations
lats = np.random.uniform(low=-90.000, high=90.000, size=1500)
lngs = np.random.uniform(low=-180.000, high=180.000, size=1500)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count
len(cities)

582

In [15]:
#API calls

weather_json=[]

for x in range(len(cities)):
    print(f"Processing Record: {x} for ID: {cities[x]}")

for city in cities:
    query_url= url + "appid=" + api_key + "&q=" + city
    time.sleep(1) 
    
    weather_response = requests.get(query_url)

    weather_json.append(weather_response.json())

Processing Record: 0 for ID: port hardy
Processing Record: 1 for ID: vaitape
Processing Record: 2 for ID: hamilton
Processing Record: 3 for ID: nioki
Processing Record: 4 for ID: samarai
Processing Record: 5 for ID: busselton
Processing Record: 6 for ID: hanzhong
Processing Record: 7 for ID: zyryanovsk
Processing Record: 8 for ID: lebu
Processing Record: 9 for ID: punta arenas
Processing Record: 10 for ID: olinda
Processing Record: 11 for ID: chiesanuova
Processing Record: 12 for ID: naze
Processing Record: 13 for ID: grindavik
Processing Record: 14 for ID: fortuna
Processing Record: 15 for ID: boyolangu
Processing Record: 16 for ID: fukue
Processing Record: 17 for ID: chokurdakh
Processing Record: 18 for ID: bandarbeyla
Processing Record: 19 for ID: provideniya
Processing Record: 20 for ID: tiksi
Processing Record: 21 for ID: strathpeffer
Processing Record: 22 for ID: necochea
Processing Record: 23 for ID: champerico
Processing Record: 24 for ID: komsomolskiy
Processing Record: 25 for ID: ushuaia
Processing Record: 26 for ID: hobart
Processing Record: 27 for ID: faanui
Processing Record: 28 for ID: cidreira
Processing Record: 29 for ID: labuhan
Processing Record: 30 for ID: vaini
Processing Record: 31 for ID: kapaa
Processing Record: 32 for ID: brandfort
Processing Record: 33 for ID: mys shmidta
Processing Record: 34 for ID: bluff
Processing Record: 35 for ID: taolanaro
Processing Record: 36 for ID: hermanus
Processing Record: 37 for ID: namikupa
Processing Record: 38 for ID: mataura
Processing Record: 39 for ID: tuktoyaktuk
Processing Record: 40 for ID: atuona
Processing Record: 41 for ID: new norfolk
Processing Record: 42 for ID: qaanaaq
Processing Record: 43 for ID: castro
Processing Record: 44 for ID: shestakovo
Processing Record: 45 for ID: clyde river
Processing Record: 46 for ID: poceirao
Processing Record: 47 for ID: rikitea
Processing Record: 48 for ID: chuy
Processing Record: 49 for ID: port elizabeth
Processing Record: 50 for ID: belushya guba
Processing Record: 51 for ID: zaoyang
Processing Record: 52 for ID: alofi
Processing Record: 53 for ID: korla
Processing Record: 54 for ID: taksimo
Processing Record: 55 for ID: longyearbyen
Processing Record: 56 for ID: gantt
Processing Record: 57 for ID: san patricio
Processing Record: 58 for ID: tasiilaq
Processing Record: 59 for ID: saint-joseph
Processing Record: 60 for ID: peleduy
Processing Record: 61 for ID: hasaki
Processing Record: 62 for ID: mount pleasant
Processing Record: 63 for ID: saint-francois
Processing Record: 64 for ID: nizhneyansk
Processing Record: 65 for ID: port alfred
Processing Record: 66 for ID: north platte
Processing Record: 67 for ID: umm lajj
Processing Record: 68 for ID: mar del plata
Processing Record: 69 for ID: vanavara
Processing Record: 70 for ID: kaitangata
Processing Record: 71 for ID: kishi
Processing Record: 72 for ID: kungurtug
Processing Record: 73 for ID: itarema
Processing Record: 74 for ID: markova
Processing Record: 75 for ID: hofn
Processing Record: 76 for ID: sol-iletsk
Processing Record: 77 for ID: lewistown
Processing Record: 78 for ID: touros
Processing Record: 79 for ID: snezhnogorsk
Processing Record: 80 for ID: tommot
Processing Record: 81 for ID: rocha
Processing Record: 82 for ID: cherskiy
Processing Record: 83 for ID: upernavik
Processing Record: 84 for ID: narsaq
Processing Record: 85 for ID: tak
Processing Record: 86 for ID: thompson
Processing Record: 87 for ID: solnechnyy
Processing Record: 88 for ID: saint george
Processing Record: 89 for ID: oktyabrskiy
Processing Record: 90 for ID: turukhansk
Processing Record: 91 for ID: acajutla
Processing Record: 92 for ID: butaritari
Processing Record: 93 for ID: avarua
Processing Record: 94 for ID: jumla
Processing Record: 95 for ID: nouadhibou
Processing Record: 96 for ID: tungkang
Processing Record: 97 for ID: illoqqortoormiut
Processing Record: 98 for ID: palizada
Processing Record: 99 for ID: grand river south east
Processing Record: 100 for ID: albany
Processing Record: 101 for ID: sabang
Processing Record: 102 for ID: harindanga
Processing Record: 103 for ID: dikson
Processing Record: 104 for ID: alta
Processing Record: 105 for ID: sorland
Processing Record: 106 for ID: kodiak
Processing Record: 107 for ID: inhambane
Processing Record: 108 for ID: geraldton
Processing Record: 109 for ID: nikolskoye
Processing Record: 110 for ID: burgersdorp
Processing Record: 111 for ID: ulaangom
Processing Record: 112 for ID: laguna
Processing Record: 113 for ID: mendeleyevsk
Processing Record: 114 for ID: padilla
Processing Record: 115 for ID: attawapiskat
Processing Record: 116 for ID: carnarvon
Processing Record: 117 for ID: kenai
Processing Record: 118 for ID: sabratah
Processing Record: 119 for ID: chicama
Processing Record: 120 for ID: areosa
Processing Record: 121 for ID: umm kaddadah
Processing Record: 122 for ID: sao filipe
Processing Record: 123 for ID: te anau
Processing Record: 124 for ID: saskylakh
Processing Record: 125 for ID: budy
Processing Record: 126 for ID: lorengau
Processing Record: 127 for ID: denau
Processing Record: 128 for ID: beringovskiy
Processing Record: 129 for ID: plettenberg bay
Processing Record: 130 for ID: bredasdorp
Processing Record: 131 for ID: esperance
Processing Record: 132 for ID: umzimvubu
Processing Record: 133 for ID: ahipara
Processing Record: 134 for ID: klaksvik
Processing Record: 135 for ID: puerto rondon
Processing Record: 136 for ID: fairbanks
Processing Record: 137 for ID: sentyabrskiy
Processing Record: 138 for ID: barentsburg
Processing Record: 139 for ID: jamestown
Processing Record: 140 for ID: cagliari
Processing Record: 141 for ID: faya
Processing Record: 142 for ID: ribeira grande
Processing Record: 143 for ID: yambio
Processing Record: 144 for ID: farmington
Processing Record: 145 for ID: deniliquin
Processing Record: 146 for ID: puerto ayora
Processing Record: 147 for ID: cape town
Processing Record: 148 for ID: ndele
Processing Record: 149 for ID: viransehir
Processing Record: 150 for ID: flinders
Processing Record: 151 for ID: hilo
Processing Record: 152 for ID: baruun-urt
Processing Record: 153 for ID: wajima
Processing Record: 154 for ID: zabaykalsk
Processing Record: 155 for ID: asyut
Processing Record: 156 for ID: auki
Processing Record: 157 for ID: vostok
Processing Record: 158 for ID: neryungri
Processing Record: 159 for ID: luderitz
Processing Record: 160 for ID: saleaula
Processing Record: 161 for ID: gavle
Processing Record: 162 for ID: ekhabi
Processing Record: 163 for ID: tasbuget
Processing Record: 164 for ID: minsk
Processing Record: 165 for ID: voznesenye
Processing Record: 166 for ID: cota
Processing Record: 167 for ID: dicabisagan
Processing Record: 168 for ID: superior
Processing Record: 169 for ID: lagoa
Processing Record: 170 for ID: tumannyy
Processing Record: 171 for ID: cabo san lucas
Processing Record: 172 for ID: korhogo
Processing Record: 173 for ID: yellowknife
Processing Record: 174 for ID: waipawa
Processing Record: 175 for ID: norman wells
Processing Record: 176 for ID: boa vista
Processing Record: 177 for ID: hobyo
Processing Record: 178 for ID: ust-nera
Processing Record: 179 for ID: ilesha
Processing Record: 180 for ID: dakar
Processing Record: 181 for ID: bremerton
Processing Record: 182 for ID: benguela
Processing Record: 183 for ID: salta
Processing Record: 184 for ID: port moresby
Processing Record: 185 for ID: kruisfontein
Processing Record: 186 for ID: taoudenni
Processing Record: 187 for ID: ormstown
Processing Record: 188 for ID: east london
Processing Record: 189 for ID: roma
Processing Record: 190 for ID: lompoc
Processing Record: 191 for ID: barbar
Processing Record: 192 for ID: severo-kurilsk
Processing Record: 193 for ID: tabuk
Processing Record: 194 for ID: mahanoro
Processing Record: 195 for ID: pisco
Processing Record: 196 for ID: minot
Processing Record: 197 for ID: pangnirtung
Processing Record: 198 for ID: vardo
Processing Record: 199 for ID: neka
Processing Record: 200 for ID: princeton
Processing Record: 201 for ID: conceicao da barra
Processing Record: 202 for ID: airai
Processing Record: 203 for ID: avera
Processing Record: 204 for ID: alice springs
Processing Record: 205 for ID: bangassou
Processing Record: 206 for ID: azimur
Processing Record: 207 for ID: palabuhanratu
Processing Record: 208 for ID: huilong
Processing Record: 209 for ID: marsh harbour
Processing Record: 210 for ID: saint-philippe
Processing Record: 211 for ID: luwuk
Processing Record: 212 for ID: gravelbourg
Processing Record: 213 for ID: samalaeulu
Processing Record: 214 for ID: marau
Processing Record: 215 for ID: steamboat springs
Processing Record: 216 for ID: nantucket
Processing Record: 217 for ID: sao joao da barra
Processing Record: 218 for ID: nuuk
Processing Record: 219 for ID: kazalinsk
Processing Record: 220 for ID: grinties
Processing Record: 221 for ID: tsihombe
Processing Record: 222 for ID: zahnitkiv
Processing Record: 223 for ID: sampit
Processing Record: 224 for ID: ilulissat
Processing Record: 225 for ID: scarborough
Processing Record: 226 for ID: twentynine palms
Processing Record: 227 for ID: envira
Processing Record: 228 for ID: batagay-alyta
Processing Record: 229 for ID: hithadhoo
Processing Record: 230 for ID: bambous virieux
Processing Record: 231 for ID: high level
Processing Record: 232 for ID: boke
Processing Record: 233 for ID: georgetown
Processing Record: 234 for ID: smolenka
Processing Record: 235 for ID: marcona
Processing Record: 236 for ID: kavieng
Processing Record: 237 for ID: bereda
Processing Record: 238 for ID: ngunguru
Processing Record: 239 for ID: san ciro de acosta
Processing Record: 240 for ID: westport
Processing Record: 241 for ID: nanortalik
Processing Record: 242 for ID: hanmer springs
Processing Record: 243 for ID: verkhnevilyuysk
Processing Record: 244 for ID: kudahuvadhoo
Processing Record: 245 for ID: torbay
Processing Record: 246 for ID: sawakin
Processing Record: 247 for ID: isangel
Processing Record: 248 for ID: vila
Processing Record: 249 for ID: yanan
Processing Record: 250 for ID: harrismith
Processing Record: 251 for ID: burica
Processing Record: 252 for ID: iqaluit
Processing Record: 253 for ID: soka
Processing Record: 254 for ID: myskhako
Processing Record: 255 for ID: mount gambier
Processing Record: 256 for ID: bethel
Processing Record: 257 for ID: maceio
Processing Record: 258 for ID: barawe
Processing Record: 259 for ID: teodoro sampaio
Processing Record: 260 for ID: mananjary
Processing Record: 261 for ID: mahebourg
Processing Record: 262 for ID: manama
Processing Record: 263 for ID: samusu
Processing Record: 264 for ID: pemberton
Processing Record: 265 for ID: brae
Processing Record: 266 for ID: onda
Processing Record: 267 for ID: bargal
Processing Record: 268 for ID: viedma
Processing Record: 269 for ID: port lavaca
Processing Record: 270 for ID: erenhot
Processing Record: 271 for ID: bilma
Processing Record: 272 for ID: arraial do cabo
Processing Record: 273 for ID: pevek
Processing Record: 274 for ID: khatanga
Processing Record: 275 for ID: gamba
Processing Record: 276 for ID: conde
Processing Record: 277 for ID: palauig
Processing Record: 278 for ID: formosa
Processing Record: 279 for ID: san policarpo
Processing Record: 280 for ID: puerto del rosario
Processing Record: 281 for ID: saint-denis
Processing Record: 282 for ID: lata
Processing Record: 283 for ID: guanica
Processing Record: 284 for ID: coquimbo
Processing Record: 285 for ID: barrow
Processing Record: 286 for ID: preobrazheniye
Processing Record: 287 for ID: kavaratti
Processing Record: 288 for ID: belaya gora
Processing Record: 289 for ID: balkanabat
Processing Record: 290 for ID: macaboboni
Processing Record: 291 for ID: kondoa
Processing Record: 292 for ID: margate
Processing Record: 293 for ID: kaduna
Processing Record: 294 for ID: talcahuano
Processing Record: 295 for ID: key largo
Processing Record: 296 for ID: codrington
Processing Record: 297 for ID: puerto narino
Processing Record: 298 for ID: katsuura
Processing Record: 299 for ID: leningradskiy
Processing Record: 300 for ID: esperantinopolis
Processing Record: 301 for ID: bilibino
Processing Record: 302 for ID: beruwala
Processing Record: 303 for ID: aklavik
Processing Record: 304 for ID: zhanaozen
Processing Record: 305 for ID: fayaoue
Processing Record: 306 for ID: roald
Processing Record: 307 for ID: beloha
Processing Record: 308 for ID: lavrentiya
Processing Record: 309 for ID: sucua
Processing Record: 310 for ID: victoria
Processing Record: 311 for ID: fort walton beach
Processing Record: 312 for ID: mizpe ramon
Processing Record: 313 for ID: shambu
Processing Record: 314 for ID: talnakh
Processing Record: 315 for ID: cururupu
Processing Record: 316 for ID: souillac
Processing Record: 317 for ID: ruatoria
Processing Record: 318 for ID: capreol
Processing Record: 319 for ID: eyl
Processing Record: 320 for ID: vestmannaeyjar
Processing Record: 321 for ID: qaqortoq
Processing Record: 322 for ID: kaniama
Processing Record: 323 for ID: rognan
Processing Record: 324 for ID: itoman
Processing Record: 325 for ID: dinguiraye
Processing Record: 326 for ID: san cristobal
Processing Record: 327 for ID: sayyan
Processing Record: 328 for ID: shiyan
Processing Record: 329 for ID: paranapanema
Processing Record: 330 for ID: vanimo
Processing Record: 331 for ID: dombarovskiy
Processing Record: 332 for ID: usoke
Processing Record: 333 for ID: bengkulu
Processing Record: 334 for ID: cairns
Processing Record: 335 for ID: aswan
Processing Record: 336 for ID: kargasok
Processing Record: 337 for ID: cap malheureux
Processing Record: 338 for ID: botwood
Processing Record: 339 for ID: tabiauea
Processing Record: 340 for ID: abu jubayhah
Processing Record: 341 for ID: ca mau
Processing Record: 342 for ID: port lincoln
Processing Record: 343 for ID: vilhena
Processing Record: 344 for ID: kedougou
Processing Record: 345 for ID: mount isa
Processing Record: 346 for ID: tikrit
Processing Record: 347 for ID: roseburg
Processing Record: 348 for ID: cuamba
Processing Record: 349 for ID: ponta do sol
Processing Record: 350 for ID: big rapids
Processing Record: 351 for ID: karakendzha
Processing Record: 352 for ID: salalah
Processing Record: 353 for ID: ossora
Processing Record: 354 for ID: colesberg
Processing Record: 355 for ID: coolum beach
Processing Record: 356 for ID: ostrovnoy
Processing Record: 357 for ID: yilan
Processing Record: 358 for ID: vila franca do campo
Processing Record: 359 for ID: berlevag
Processing Record: 360 for ID: nizwa
Processing Record: 361 for ID: richards bay
Processing Record: 362 for ID: williston
Processing Record: 363 for ID: karanja
Processing Record: 364 for ID: luanda
Processing Record: 365 for ID: vrangel
Processing Record: 366 for ID: dawei
Processing Record: 367 for ID: phan rang
Processing Record: 368 for ID: gorontalo
Processing Record: 369 for ID: zwedru
Processing Record: 370 for ID: huarmey
Processing Record: 371 for ID: ambilobe
Processing Record: 372 for ID: baie-comeau
Processing Record: 373 for ID: venice
Processing Record: 374 for ID: santo domingo
Processing Record: 375 for ID: zhigansk
Processing Record: 376 for ID: dolbeau
Processing Record: 377 for ID: general roca
Processing Record: 378 for ID: altay
Processing Record: 379 for ID: kalundborg
Processing Record: 380 for ID: jinchengjiang
Processing Record: 381 for ID: maniitsoq
Processing Record: 382 for ID: poum
Processing Record: 383 for ID: havelock
Processing Record: 384 for ID: antofagasta
Processing Record: 385 for ID: cabo rojo
Processing Record: 386 for ID: zeya
Processing Record: 387 for ID: hualmay
Processing Record: 388 for ID: qasigiannguit
Processing Record: 389 for ID: mitzic
Processing Record: 390 for ID: chifeng
Processing Record: 391 for ID: jaru
Processing Record: 392 for ID: haines junction
Processing Record: 393 for ID: saldanha
Processing Record: 394 for ID: dostpur
Processing Record: 395 for ID: iberia
Processing Record: 396 for ID: talas
Processing Record: 397 for ID: chagda
Processing Record: 398 for ID: bud
Processing Record: 399 for ID: sisimiut
Processing Record: 400 for ID: ratnagiri
Processing Record: 401 for ID: wageningen
Processing Record: 402 for ID: palana
Processing Record: 403 for ID: verkhoyansk
Processing Record: 404 for ID: tuatapere
Processing Record: 405 for ID: arona
Processing Record: 406 for ID: vacaville
Processing Record: 407 for ID: syracuse
Processing Record: 408 for ID: polis
Processing Record: 409 for ID: hanover
Processing Record: 410 for ID: lasa
Processing Record: 411 for ID: poya
Processing Record: 412 for ID: amderma
Processing Record: 413 for ID: sena madureira
Processing Record: 414 for ID: bocas del toro
Processing Record: 415 for ID: hearst
Processing Record: 416 for ID: tuy hoa
Processing Record: 417 for ID: west bay
Processing Record: 418 for ID: vaitupu
Processing Record: 419 for ID: kegayli
Processing Record: 420 for ID: goya
Processing Record: 421 for ID: hovd
Processing Record: 422 for ID: sinegorskiy
Processing Record: 423 for ID: porto velho
Processing Record: 424 for ID: carman
Processing Record: 425 for ID: comodoro rivadavia
Processing Record: 426 for ID: sinegorye
Processing Record: 427 for ID: idaho falls
Processing Record: 428 for ID: alekseyevsk
Processing Record: 429 for ID: tezpur
Processing Record: 430 for ID: pervomayskiy
Processing Record: 431 for ID: aginskoye
Processing Record: 432 for ID: lysyye gory
Processing Record: 433 for ID: meyungs
Processing Record: 434 for ID: dese
Processing Record: 435 for ID: tubruq
Processing Record: 436 for ID: kahului
Processing Record: 437 for ID: buchanan
Processing Record: 438 for ID: plaisance-du-touch
Processing Record: 439 for ID: dudinka
Processing Record: 440 for ID: iisalmi
Processing Record: 441 for ID: san vicente
Processing Record: 442 for ID: manthani
Processing Record: 443 for ID: concepcion batres
Processing Record: 444 for ID: yar-sale
Processing Record: 445 for ID: saint-pierre
Processing Record: 446 for ID: nichlaul
Processing Record: 447 for ID: katangli
Processing Record: 448 for ID: manicore
Processing Record: 449 for ID: buala
Processing Record: 450 for ID: wanaka
Processing Record: 451 for ID: kifri
Processing Record: 452 for ID: flagstaff
Processing Record: 453 for ID: sola
Processing Record: 454 for ID: nador
Processing Record: 455 for ID: timbiqui
Processing Record: 456 for ID: caravelas
Processing Record: 457 for ID: dzhebariki-khaya
Processing Record: 458 for ID: sholokhovskiy
Processing Record: 459 for ID: wenceslau braz
Processing Record: 460 for ID: robertsport
Processing Record: 461 for ID: mrirt
Processing Record: 462 for ID: corozal
Processing Record: 463 for ID: launceston
Processing Record: 464 for ID: chyhyryn
Processing Record: 465 for ID: sao jose da coroa grande
Processing Record: 466 for ID: rungata
Processing Record: 467 for ID: buren
Processing Record: 468 for ID: matara
Processing Record: 469 for ID: jablah
Processing Record: 470 for ID: holme
Processing Record: 471 for ID: ternate
Processing Record: 472 for ID: camacha
Processing Record: 473 for ID: kushmurun
Processing Record: 474 for ID: bordighera
Processing Record: 475 for ID: jibuti
Processing Record: 476 for ID: guiglo
Processing Record: 477 for ID: coshocton
Processing Record: 478 for ID: nome
Processing Record: 479 for ID: perevoz
Processing Record: 480 for ID: petropavlovsk-kamchatskiy
Processing Record: 481 for ID: kuching
Processing Record: 482 for ID: anadyr
Processing Record: 483 for ID: yairipok
Processing Record: 484 for ID: asau
Processing Record: 485 for ID: nakamura
Processing Record: 486 for ID: padang
Processing Record: 487 for ID: enugu
Processing Record: 488 for ID: marabba
Processing Record: 489 for ID: los llanos de aridane
Processing Record: 490 for ID: mackay
Processing Record: 491 for ID: deputatskiy
Processing Record: 492 for ID: arawa
Processing Record: 493 for ID: zastron
Processing Record: 494 for ID: coihaique
Processing Record: 495 for ID: kieta

In [19]:
weather_json
json_normalize(weather_json)

,base,clouds.all,cod,coord.lat,coord.lon,dt,id,main.grnd_level,main.humidity,main.pressure,...,sys.id,sys.message,sys.sunrise,sys.sunset,sys.type,visibility,weather,wind.deg,wind.gust,wind.speed
0,stations,20.0,200,50.70,-127.42,1.552939e+09,6111862.0,NaN,76.0,1022.00,...,1011.0,0.0058,1.552920e+09,1.552963e+09,1.0,32186.0,"[{'id': 801, 'main': 'Clouds', 'description': ...",20.0000,NaN,1.50
1,stations,0.0,200,-16.52,-151.75,1.552941e+09,4033077.0,1010.84,100.0,1011.59,...,NaN,0.0033,1.552925e+09,1.552969e+09,NaN,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",189.0000,NaN,0.61
2,stations,90.0,200,32.30,-64.78,1.552940e+09,3573197.0,NaN,87.0,1017.00,...,8816.0,0.0051,1.552905e+09,1.552948e+09,1.0,10000.0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",50.0000,NaN,6.70
3,stations,36.0,200,-2.72,17.69,1.552941e+09,2311968.0,973.24,90.0,1008.87,...,NaN,0.0033,1.552885e+09,1.552928e+09,NaN,NaN,"[{'id': 802, 'main': 'Clouds', 'description': ...",351.5000,NaN,0.61
4,stations,80.0,200,-10.62,150.67,1.552941e+09,2132606.0,1005.96,100.0,1009.07,...,NaN,0.0038,1.552939e+09,1.552983e+09,NaN,NaN,"[{'id': 803, 'main': 'Clouds', 'description': ...",96.5001,NaN,0.91
5,stations,8.0,200,-33.64,115.35,1.552941e+09,2075265.0,NaN,38.0,1003.00,...,2011706.0,0.0032,1.552948e+09,1.552992e+09,3.0,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",21.5001,NaN,4.59
6,stations,68.0,200,33.08,107.03,1.552941e+09,1808857.0,899.24,87.0,1007.51,...,NaN,0.0039,1.552950e+09,1.552993e+09,NaN,NaN,"[{'id': 803, 'main': 'Clouds', 'description': ...",105.0000,NaN,0.91
7,stations,0.0,200,49.74,84.27,1.552941e+09,1516438.0,931.16,69.0,1030.71,...,NaN,0.0028,1.552955e+09,1.552999e+09,NaN,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",354.5000,NaN,0.91
8,stations,0.0,200,8.96,38.73,1.552941e+09,344979.0,768.60,59.0,1011.03,...,NaN,0.0033,1.552880e+09,1.552923e+09,NaN,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",69.0001,NaN,2.69
9,stations,40.0,200,-53.16,-70.91,1.552941e+09,3874787.0,NaN,92.0,1007.00,...,8487.0,0.0047,1.552906e+09,1.552950e+09,1.0,10000.0,"[{'id': 802, 'main': 'Clouds', 'description': ...",230.0000,NaN,11.30
10,stations,75.0,200,-2.03,-79.75,1.552941e+09,3650121.0,NaN,70.0,1006.00,...,8534.0,0.0038,1.552908e+09,1.552952e+09,1.0,10000.0,"[{'id': 520, 'main': 'Rain', 'description': 'l...",130.0000,NaN,2.10
11,stations,75.0,200,43.91,12.42,1.552941e+09,6457404.0,NaN,93.0,1017.00,...,6770.0,0.0057,1.552886e+09,1.552930e+09,1.0,5000.0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",290.0000,NaN,3.60
12,stations,75.0,200,5.43,7.07,1.552939e+09,2337542.0,NaN,83.0,1009.00,...,1170.0,0.0038,1.552887e+09,1.552931e+09,1.0,8000.0,"[{'id': 211, 'main': 'Thunderstorm', 'descript...",220.0000,NaN,2.10
13,stations,75.0,200,63.84,-22.43,1.552939e+09,3416888.0,NaN,93.0,989.00,...,90.0,0.0046,1.552895e+09,1.552938e+09,1.0,10000.0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",190.0000,NaN,12.90
14,stations,75.0,200,38.18,-1.13,1.552941e+09,2517679.0,NaN,62.0,1024.00,...,6391.0,0.0046,1.552890e+09,1.552933e+09,1.0,10000.0,"[{'id': 803, 'main': 'Clouds', 'description': ...",10.0000,NaN,2.60
15,stations,44.0,200,-8.09,111.90,1.552941e+09,1648082.0,965.88,93.0,1008.71,...,NaN,0.0038,1.552949e+09,1.552992e+09,NaN,NaN,"[{'id': 802, 'main': 'Clouds', 'description': ...",189.0000,NaN,1.04
16,stations,75.0,200,35.03,136.69,1.552941e+09,1848373.0,NaN,61.0,1018.00,...,8009.0,0.0050,1.552943e+09,1.552986e+09,1.0,10000.0,"[{'id': 803, 'main': 'Clouds', 'description': ...",360.0000,NaN,4.60
17,stations,48.0,200,70.62,147.90,1.552941e+09,2126123.0,1021.00,62.0,1023.27,...,NaN,0.0031,1.552940e+09,1.552983e+09,NaN,NaN,"[{'id': 802, 'main': 'Clouds', 'description': ...",247.5000,NaN,1.34
18,stations,92.0,200,9.49,50.81,1.552941e+09,64814.0,1008.84,100.0,1013.87,...,NaN,0.0037,1.552877e+09,1.552920e+09,NaN,NaN,"[{'id': 804, 'main': 'Clouds', 'description': ...",56.0001,NaN,3.91
19,stations,8.0,200,64.42,-173.23,1.552941e+09,4031574.0,997.08,100.0,1003.71,...,NaN,0.0044,1.553017e+09,1.553061e+09,NaN,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",301.5000,NaN,3.09
20,stations,20.0,200,71.64,128.87,1.552941e+09,2015306.0,1003.64,38.0,1023.15,...,NaN,0.0044,1.552945e+09,1.552988e+09,NaN,NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...",293.5000,NaN,1.49
21,stations,20.0,200,57.59,-4.54,1.552941e+09,2651245.0,NaN,86.0,1018.00,...,1435.0,0.0043,1.552890e+09,1.552934e+09,1.0,10000.0,"[{'id': 801, 'main': 'Clouds', 'description': ...",230.0000,NaN,3.60
22,stations,0.0,200,-38.55,-58.74,1.552941e+09,3430443.0,NaN,53.0,1008.00,...,2006665.0,0.0038,1.552903e+09,1.552947e+09,3.0,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",247.0000,5.36,2.68
23,stations,40.0,200,16.38,-93.60,1.552938e+09,3530097.0,NaN,45.0,1015.00,...,7162.0,0.0042,1.552912e+09,1.552955e+09,1.0,16093.0,"[{'id': 711, 'main': 'Smoke', 'description': '...",320.0000,NaN,7.70
24,stations,80.0,200,67.55,63.78,1.552941e+09,1486910.0,1000.28,89.0,1021.19,...,NaN,0.0041,1.552874e+09,1.552917e+09,NaN,NaN,"[{'id': 803, 'main': 'Clouds', 'description': ...",222.5000,NaN,5.21
25,stations,75.0,200,-54.81,-68.31,1.552936e+09,3833367.0,NaN,94.0,1006.00,...,8303.0,0.0047,1.552905e+09,1.552950e+09,1.0,10000.0,"[{'id': 803, 'main': 'Clouds', 'description': ...",230.0000,NaN,7.20
26,stations,75.0,200,-42.88,147.33,1.552941e+09,2163355.0,NaN,87.0,1020.00,...,9545.0,0.0050,1.552940e+09,1.552984e+09,1.0,10000.0,"[{'id': 803, 'main': 'Clouds', 'description': ...",300.0000,NaN,3.10
27,stations,20.0,200,-16.48,-151.75,1.552941e+09,4034551.0,1011.48,100.0,1011.55,...,NaN,0.0034,1.552925e+09,1.552969e+09,NaN,NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...",132.0000,NaN,1.79
28,stations,76.0,200,-30.17,-50.22,1.552941e+09,3466165.0,996.36,96.0,1006.15,...,NaN,0.0032,1.552901e+09,1.552945e+09,NaN,NaN,"[{'id': 500, 'main': 'Rain', 'description': 'l...",275.0000,NaN,6.61
29,stations,36.0,200,-2.54,115.51,1.552941e+09,1641899.0,983.96,94.0,1009.43,...,NaN,0.0127,1.552948e+09,1.552991e+09,NaN,NaN,"[{'id': 802, 'main': 'Clouds', 'description': ...",243.5000,NaN,0.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,NaN,NaN,404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553,stations,0.0,200,45.06,34.59,1.552942e+09,712587.0,992.36,100.0,1024.03,...,NaN,0.0032,1.552881e+09,1.552924e+09,NaN,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",154.5000,NaN,3.04
554,stations,0.0,200,52.13,46.08,1.552939e+09,517172.0,NaN,86.0,1027.00,...,9048.0,0.0034,1.552965e+09,1.553008e+09,1.0,10000.0,"[{'id': 800, 'main': 'Clear', 'description': '...",130.0000,NaN,1.00
555,stations,0.0,200,14.69,-16.54,1.552939e+09,2249901.0,NaN,34.0,1009.00,...,2410.0,0.0032,1.552893e+09,1.552937e+09,1.0,8000.0,"[{'id': 800, 'main': 'Clear', 'description': '...",350.0000,NaN,6.70
556,stations,0.0,200,59.77,30.80,1.552942e+09,513898.0,NaN,93.0,1007.00,...,8926.0,0.0610,1.552882e+09,1.552925e+09,1.0,10000.0,"[{'id': 800, 'main': 'Clear', 'description': '...",200.0000,NaN,2.00
557,stations,20.0,200,40.99,23.67,1.552942e+09,734330.0,NaN,74.0,1017.00,...,20187.0,0.0039,1.552884e+09,1.552927e+09,3.0,NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...",248.0000,1.34,0.45
558,stations,100.0,200,5.79,36.57,1.552942e+09,333750.0,848.52,40.0,1006.71,...,NaN,0.0049,1.552880e+09,1.552924e+09,NaN,NaN,"[{'id': 804, 'main': 'Clouds', 'description': ...",151.0000,NaN,0.76
559,NaN,NaN,404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
560,NaN,NaN,404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
561,stations,0.0,200,57.78,108.12,1.552942e+09,2022083.0,971.40,65.0,1025.75,...,NaN,0.0047,1.552950e+09,1.552993e+09,NaN,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",292.0000,NaN,1.06
562,stations,8.0,200,-39.00,175.93,1.552942e+09,2180737.0,NaN,56.0,1022.00,...,2002626.0,0.0035,1.552933e+09,1.552977e+09,3.0,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",119.0000,1.34,0.89
563,stations,0.0,200,42.02,121.65,1.552942e+09,2037346.0,983.48,71.0,1005.63,...,NaN,0.0030,1.552946e+09,1.552990e+09,NaN,NaN,"[{'id': 800, 'main': 'Clear', 'description': '...",194.5000,NaN,3.94
564,stations,80.0,200,26.25,105.93,1.552942e+09,1817968.0,862.36,96.0,1007.83,...,NaN,0.0040,1.552950e+09,1.552994e+09,NaN,NaN,"[{'id': 803, 'main': 'Clouds', 'description': ...",177.5000,NaN,5.71
565,stations,75.0,200,44.65,-63.58,1.552941e+09,6324729.0,NaN,37.0,1018.00,...,733.0,0.0042,1.552905e+09,1.552948e+09,1.0,24140.0,"[{'id': 803, 'main': 'Clouds', 'description': ...",240.0000,9.80,7.20
566,stations,44.0,200,20.52,-13.05,1.552942e+09,2381334.0,982.60,12.0,1012.27,...,NaN,0.0043,1.552892e+09,1.552936e+09,NaN,NaN,"[{'id': 802, 'main': 'Clouds', 'description': ...",29.5001,NaN,3.26
567,stations,40.0,200,47.58,-53.28,1.552942e+09,5895424.0,NaN,50.0,1015.00,...,998.0,0.0046,1.552902e+09,1.552945e+09,1.0,24140.0,"[{'id': 802, 'main': 'Clouds', 'description': ...",260.0000,11.30,8.20
568,stations,0.0,200,-25.24,130.99,1.552939e+09,6355222.0,NaN,25.0,1013.00,...,9487.0,0.0040,1.552944e+09,1.552988e+09,1.0,10000.0,"[{'id': 800, 'main': 'Clear', 'description': '...",130.0000,NaN,4.10
569,stations,1.0,200,43.97,-111.68,1.552942e+09,5606187.0,NaN,36.0,1024.00,...,5735.0,0.0061,1.552916e+09,1.552959e+09,1.0,16093.0,"[{'id': 800, 'main': 'Clear', 'description': '...",NaN,NaN,2.10
570,stations,80.0,200,-14.66,17.68,1.552942e+09,3347353.0,853.08,75.0,1007.83,...,NaN,0.0034,1.552885e+09,1.552929e+09,NaN,NaN,"[{'id': 803, 'main': 'Clouds', 'description': ...",50.0001,NaN,0.36
571,NaN,NaN,404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
572,stations,12.0,200,29.72,112.52,1.552942e+09,1788268.0,1009.08,84.0,1012.71,...,NaN,0.0080,1.552949e+09,1.552992e+09,NaN,NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...",138.0000,NaN,3.69
573,stations,76.0,200,54.33,80.49,1.552942e+09,1503061.0,1015.64,80.0,1035.47,...,NaN,0.0037,1.552956e+09,1.553000e+09,NaN,NaN,"[{'id': 803, 'main': 'Clouds', 'description': ...",236.0000,NaN,1.69
574,stations,64.0,200,11.00,122.67,1.552942e+09,1714733.0,990.76,88.0,1010.71,...,NaN,0.0033,1.552946e+09,1.552990e+09,NaN,NaN,"[{'id': 500, 'main': 'Rain', 'description': 'l...",41.0001,NaN,4.81
575,stations,32.0,200,-2.55,14.76,1.552942e+09,2260401.0,941.40,94.0,1010.03,...,NaN,0.0033,1.552886e+09,1.552929e+09,NaN,NaN,"[{'id': 802, 'main': 'Clouds', 'description': ...",314.5000,NaN,2.01
576,stations,20.0,200,-25.87,29.23,1.552942e+09,939270.0,849.72,91.0,1013.15,...,NaN,0.0035,1.552882e+09,1.552926e+09,NaN,NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...",112.0000,NaN,1.24
577,stations,40.0,200,33.60,-7.62,1.552941e+09,2553604.0,NaN,82.0,1020.00,...,2386.0,0.0050,1.552891e+09,1.552934e+09,1.0,10000.0,"[{'id': 802, 'main': 'Clouds', 'description': ...",40.0000,NaN,4.60
578,stations,64.0,200,4.14,96.13,1.552942e+09,1214488.0,1007.64,100.0,1009.87,...,NaN,0.0037,1.552952e+09,1.552996e+09,NaN,NaN,"[{'id': 803, 'main': 'Clouds', 'description': ...",30.5001,NaN,1.49
579,stations,12.0,200,-3.66,152.44,1.552942e+09,2090021.0,1003.00,100.0,1008.79,...,NaN,0.0037,1.552939e+09,1.552983e+09,NaN,NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...",252.0000,NaN,4.36
580,stations,75.0,200,48.86,-53.99,1.552941e+09,5970873.0,NaN,49.0,1013.00,...,912.0,0.0117,1.552902e+09,1.552945e+09,1.0,32186.0,"[{'id': 803, 'main': 'Clouds', 'description': ...",240.0000,10.30,7.20
581,NaN,NaN,404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#weather_df = pd.DataFrame(weather_json)
#weather_df

,base,clouds,cod,coord,dt,id,main,message,name,rain,snow,sys,visibility,weather,wind
0,stations,{'all': 44},200,"{'lon': 115.35, 'lat': -33.64}",1.552909e+09,2075265.0,"{'temp': 298.23, 'pressure': 1004, 'humidity':...",NaN,Busselton,NaN,NaN,"{'type': 3, 'id': 2011706, 'message': 0.0036, ...",NaN,"[{'id': 802, 'main': 'Clouds', 'description': ...","{'speed': 0.69, 'deg': 10.001}"
1,stations,{'all': 1},200,"{'lon': -119.31, 'lat': 36.62}",1.552909e+09,5379533.0,"{'temp': 282.46, 'pressure': 1016, 'humidity':...",NaN,Orange Cove,NaN,NaN,"{'type': 1, 'id': 5145, 'message': 0.0049, 'co...",16093.0,"[{'id': 701, 'main': 'Mist', 'description': 'm...","{'speed': 1.27, 'deg': 99.501}"
2,stations,{'all': 20},200,"{'lon': 153.71, 'lat': 67.46}",1.552909e+09,2121025.0,"{'temp': 244.365, 'pressure': 1021.63, 'humidi...",NaN,Srednekolymsk,NaN,NaN,"{'message': 0.0047, 'country': 'RU', 'sunrise'...",NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...","{'speed': 1.44, 'deg': 331.001}"
3,stations,{'all': 24},200,"{'lon': 19.24, 'lat': -34.42}",1.552909e+09,3366880.0,"{'temp': 298.83, 'pressure': 1010, 'humidity':...",NaN,Hermanus,{},NaN,"{'type': 3, 'id': 2003650, 'message': 0.0034, ...",NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...","{'speed': 2.68, 'deg': 187, 'gust': 4.92}"
4,stations,{'all': 0},200,"{'lon': 81.45, 'lat': 25.14}",1.552909e+09,1276986.0,"{'temp': 300.215, 'pressure': 1011.19, 'humidi...",NaN,Bargarh,NaN,NaN,"{'message': 0.003, 'country': 'IN', 'sunrise':...",NaN,"[{'id': 800, 'main': 'Clear', 'description': '...","{'speed': 1.72, 'deg': 344.001}"
5,stations,{'all': 75},200,"{'lon': -68.31, 'lat': -54.81}",1.552907e+09,3833367.0,"{'temp': 278.15, 'pressure': 999, 'humidity': ...",NaN,Ushuaia,NaN,NaN,"{'type': 1, 'id': 8303, 'message': 0.0043, 'co...",10000.0,"[{'id': 300, 'main': 'Drizzle', 'description':...","{'speed': 10.8, 'deg': 140}"
6,NaN,NaN,404,NaN,NaN,NaN,NaN,city not found,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,stations,{'all': 92},200,"{'lon': -139.03, 'lat': -9.8}",1.552909e+09,4020109.0,"{'temp': 300.665, 'pressure': 1009.43, 'humidi...",NaN,Atuona,{'3h': 0.12},NaN,"{'message': 0.004, 'country': 'PF', 'sunrise':...",NaN,"[{'id': 500, 'main': 'Rain', 'description': 'l...","{'speed': 6.17, 'deg': 117.001}"
8,stations,{'all': 56},200,"{'lon': 159.95, 'lat': 59.08}",1.552909e+09,2122262.0,"{'temp': 258.615, 'pressure': 1005.75, 'humidi...",NaN,Palana,NaN,NaN,"{'message': 0.0044, 'country': 'RU', 'sunrise'...",NaN,"[{'id': 803, 'main': 'Clouds', 'description': ...","{'speed': 2.52, 'deg': 205.001}"
9,stations,{'all': 75},200,"{'lon': -73.75, 'lat': 42.65}",1.552909e+09,5106834.0,"{'temp': 267.95, 'pressure': 1024, 'humidity':...",NaN,Albany,NaN,NaN,"{'type': 1, 'id': 3273, 'message': 0.0068, 'co...",16093.0,"[{'id': 803, 'main': 'Clouds', 'description': ...","{'speed': 3.6, 'deg': 280}"
10,stations,{'all': 24},200,"{'lon': 108.12, 'lat': 57.78}",1.552909e+09,2022083.0,"{'temp': 264.965, 'pressure': 1022.91, 'humidi...",NaN,Kirensk,NaN,NaN,"{'message': 0.0035, 'country': 'RU', 'sunrise'...",NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...","{'speed': 2.57, 'deg': 13.001}"
11,stations,{'all': 36},200,"{'lon': -90.35, 'lat': -0.74}",1.552909e+09,3652764.0,"{'temp': 296.115, 'pressure': 1010.27, 'humidi...",NaN,Puerto Ayora,NaN,NaN,"{'message': 0.0031, 'country': 'EC', 'sunrise'...",NaN,"[{'id': 802, 'main': 'Clouds', 'description': ...","{'speed': 1.27, 'deg': 240.501}"
12,stations,{'all': 24},200,"{'lon': -46, 'lat': -20.63}",1.552909e+09,3453439.0,"{'temp': 297.665, 'pressure': 1012.47, 'humidi...",NaN,Ponta do Sol,NaN,NaN,"{'message': 0.0035, 'country': 'BR', 'sunrise'...",NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...","{'speed': 1.97, 'deg': 28.001}"
13,stations,{'all': 75},200,"{'lon': 65.69, 'lat': 40.56}",1.552907e+09,1513087.0,"{'temp': 296.15, 'pressure': 1001, 'humidity':...",NaN,Nurota,NaN,NaN,"{'type': 1, 'id': 9007, 'message': 0.0033, 'co...",2400.0,"[{'id': 803, 'main': 'Clouds', 'description': ...","{'speed': 9.3, 'deg': 200}"
14,stations,{'all': 75},200,"{'lon': -35.46, 'lat': -5.2}",1.552907e+09,3386213.0,"{'temp': 298.15, 'pressure': 1014, 'humidity':...",NaN,Touros,NaN,NaN,"{'type': 1, 'id': 8452, 'message': 0.0043, 'co...",8000.0,"[{'id': 803, 'main': 'Clouds', 'description': ...",{'speed': 0.5}
15,stations,{'all': 20},200,"{'lon': -45.25, 'lat': -5.5}",1.552909e+09,3406318.0,"{'temp': 300.965, 'pressure': 1013.19, 'humidi...",NaN,Barra do Corda,NaN,NaN,"{'message': 0.0034, 'country': 'BR', 'sunrise'...",NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...","{'speed': 2.12, 'deg': 321.001}"
16,stations,{'all': 92},200,"{'lon': 32.62, 'lat': -20.19}",1.552909e+09,893549.0,"{'temp': 294.465, 'pressure': 1009.31, 'humidi...",NaN,Chipinge,{'3h': 2.6975},NaN,"{'message': 0.0032, 'country': 'ZW', 'sunrise'...",NaN,"[{'id': 500, 'main': 'Rain', 'description': 'l...","{'speed': 2.17, 'deg': 170.001}"
17,stations,{'all': 48},200,"{'lon': 143.24, 'lat': 59.36}",1.552909e+09,2122605.0,"{'temp': 259.765, 'pressure': 1012.55, 'humidi...",NaN,Okhotsk,NaN,NaN,"{'message': 0.0042, 'country': 'RU', 'sunrise'...",NaN,"[{'id': 802, 'main': 'Clouds', 'description': ...","{'speed': 1.84, 'deg': 64.001}"
18,stations,{'all': 0},200,"{'lon': 153.24, 'lat': -28.95}",1.552909e+09,2160063.0,"{'temp': 294.18, 'pressure': 1012, 'humidity':...",NaN,Codrington,NaN,NaN,"{'type': 1, 'id': 9537, 'message': 0.0047, 'co...",10000.0,"[{'id': 800, 'main': 'Clear', 'description': '...","{'speed': 1.02, 'deg': 270.001}"
19,stations,{'all': 76},200,"{'lon': 102.47, 'lat': 71.98}",1.552909e+09,2022572.0,"{'temp': 257.365, 'pressure': 1020.51, 'humidi...",NaN,Khatanga,NaN,NaN,"{'message': 0.0036, 'country': 'RU', 'sunrise'...",NaN,"[{'id': 803, 'main': 'Clouds', 'description': ...","{'speed': 3.19, 'deg': 217.501}"
20,NaN,NaN,404,NaN,NaN,NaN,NaN,city not found,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,stations,{'all': 90},200,"{'lon': -52.1, 'lat': -32.03}",1.552907e+09,3451138.0,"{'temp': 295.15, 'pressure': 1007, 'humidity':...",NaN,Rio Grande,NaN,NaN,"{'type': 1, 'id': 8408, 'message': 0.0034, 'co...",10000.0,"[{'id': 804, 'main': 'Clouds', 'description': ...","{'speed': 3.69, 'deg': 356.001}"
22,stations,{'all': 75},200,"{'lon': 129.49, 'lat': 33.32}",1.552909e+09,1862555.0,"{'temp': 285.43, 'pressure': 1017, 'humidity':...",NaN,Hirado,NaN,NaN,"{'type': 1, 'id': 8000, 'message': 0.0035, 'co...",10000.0,"[{'id': 803, 'main': 'Clouds', 'description': ...","{'speed': 1, 'deg': 360}"
23,stations,{'all': 8},200,"{'lon': -67.52, 'lat': -46.43}",1.552909e+09,3863379.0,"{'temp': 283.365, 'pressure': 1005.39, 'humidi...",NaN,Mar del Plata,NaN,NaN,"{'message': 0.0037, 'country': 'AR', 'sunrise'...",NaN,"[{'id': 800, 'main': 'Clear', 'description': '...","{'speed': 8.54, 'deg': 255.501}"
24,stations,{'all': 0},200,"{'lon': -170.99, 'lat': 65.58}",1.552909e+09,4031637.0,"{'temp': 253.965, 'pressure': 1001.79, 'humidi...",NaN,Lavrentiya,NaN,NaN,"{'message': 0.0029, 'country': 'RU', 'sunrise'...",NaN,"[{'id': 800, 'main': 'Clear', 'description': '...","{'speed': 3.32, 'deg': 215.501}"
25,stations,{'all': 0},200,"{'lon': 1.37, 'lat': 42.87}",1.552909e+09,3036965.0,"{'temp': 284.34, 'pressure': 1022, 'humidity':...",NaN,Le Port,NaN,NaN,"{'type': 1, 'id': 6426, 'message': 0.006, 'cou...",10000.0,"[{'id': 800, 'main': 'Clear', 'description': '...",{'speed': 2.6}
26,stations,{'all': 20},200,"{'lon': 147.06, 'lat': -42.78}",1.552909e+09,2155415.0,"{'temp': 286.95, 'pressure': 1022, 'humidity':...",NaN,New Norfolk,NaN,NaN,"{'type': 1, 'id': 9545, 'message': 0.0034, 'co...",10000.0,"[{'id': 801, 'main': 'Clouds', 'description': ...","{'speed': 2.6, 'deg': 90}"
27,stations,{'all': 40},200,"{'lon': 121, 'lat': 15.35}",1.552907e+09,1694075.0,"{'temp': 302.15, 'pressure': 1013, 'humidity':...",NaN,Penaranda,NaN,NaN,"{'type': 1, 'id': 8152, 'message': 0.0039, 'co...",10000.0,"[{'id': 802, 'main': 'Clouds', 'description': ...","{'speed': 3.1, 'deg': 110}"
28,stations,{'all': 92},200,"{'lon': -37.64, 'lat': 65.61}",1.552906e+09,3424607.0,"{'temp': 267.15, 'pressure': 983, 'humidity': ...",NaN,Tasiilaq,NaN,NaN,"{'type': 1, 'id': 81, 'message': 0.0042, 'coun...",NaN,"[{'id': 600, 'main': 'Snow', 'description': 'l...","{'speed': 10.3, 'deg': 130}"
29,NaN,NaN,404,NaN,NaN,NaN,NaN,city not found,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,stations,{'all': 20},200,"{'lon': -79.1, 'lat': 46.72}",1.552909e+09,6162654.0,"{'temp': 257.51, 'pressure': 1022, 'humidity':...",NaN,Temiscaming,NaN,NaN,"{'type': 1, 'id': 988, 'message': 0.0047, 'cou...",24140.0,"[{'id': 801, 'main': 'Clouds', 'description': ...","{'speed': 3.6, 'deg': 20}"
605,NaN,NaN,404,NaN,NaN,NaN,NaN,city not found,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606,stations,{'all': 88},200,"{'lon': 54.27, 'lat': 53.69}",1.552910e+09,576195.0,"{'temp': 273.515, 'pressure': 1025.75, 'humidi...",NaN,Bizhbulyak,NaN,NaN,"{'message': 0.0047, 'country': 'RU', 'sunrise'...",NaN,"[{'id': 804, 'main': 'Clouds', 'description': ...","{'speed': 3.59, 'deg': 63.501}"
607,stations,{'all': 75},200,"{'lon': -78.88, 'lat': 41.39}",1.552910e+09,5208292.0,"{'temp': 268.61, 'pressure': 1023, 'humidity':...",NaN,Arroyo,NaN,NaN,"{'type': 1, 'id': 5262, 'message': 0.0042, 'co...",16093.0,"[{'id': 803, 'main': 'Clouds', 'description': ...","{'speed': 0.84, 'deg': 285.501}"
608,stations,{'all': 20},200,"{'lon': -64.62, 'lat': 18.42}",1.552910e+09,3577430.0,"{'temp': 298.21, 'pressure': 1016, 'humidity':...",NaN,Road Town,NaN,NaN,"{'type': 1, 'id': 8799, 'message': 0.0036, 'co...",16093.0,"[{'id': 801, 'main': 'Clouds', 'description': ...","{'speed': 4.6, 'deg': 130}"
609,stations,{'all': 0},200,"{'lon': 73.76, 'lat': 43.6}",1.552910e+09,1519030.0,"{'temp': 287.215, 'pressure': 1010.59, 'humidi...",NaN,Shu,NaN,NaN,"{'message': 0.0037, 'country': 'KZ', 'sunrise'...",NaN,"[{'id': 800, 'main': 'Clear', 'description': '...","{'speed': 11.12, 'deg': 68.501}"
610,NaN,NaN,404,NaN,NaN,NaN,NaN,city not found,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,stations,{'all': 0},200,"{'lon': 101.72, 'lat': 26.59}",1.552907e+09,6929460.0,"{'temp': 295.37, 'pressure': 809, 'humidity': ...",NaN,Panzhihua,NaN,NaN,"{'type': 3, 'id': 2000456, 'message': 0.0044, ...",NaN,"[{'id': 800, 'main': 'Clear', 'description': '...","{'speed': 3.32, 'deg': 208.001}"
612,stations,{'all': 0},200,"{'lon': 20.22, 'lat': 30.75}",1.552910e+09,89113.0,"{'temp': 298.615, 'pressure': 1018.03, 'humidi...",NaN,Ajdabiya,NaN,NaN,"{'message': 0.0041, 'country': 'LY', 'sunrise'...",NaN,"[{'id': 800, 'main': 'Clear', 'description': '...","{'speed': 3.59, 'deg': 247.001}"
613,stations,{'all': 0},200,"{'lon': 6.97, 'lat': 43.56}",1.552910e+09,3037456.0,"{'temp': 286.5, 'pressure': 1015, 'humidity': ...",NaN,Saint-Joseph,NaN,NaN,"{'type': 1, 'id': 6507, 'message': 0.0045, 'co...",10000.0,"[{'id': 800, 'main': 'Clear', 'description': '...",{'speed': 1}
614,stations,{'all': 75},200,"{'lon': 103.39, 'lat': 3.49}",1.552907e+09,1734971.0,"{'temp': 303.15, 'pressure': 1009, 'humidity':...",NaN,Pekan,NaN,NaN,"{'type': 1, 'id': 9432, 'message': 0.0033, 'co...",10000.0,"[{'id': 803, 'main': 'Clouds', 'description': ...",{'speed': 3.1}
615,stations,{'all': 75},200,"{'lon': 121.74, 'lat': 25.13}",1.552910e+09,1678228.0,"{'temp': 293.86, 'pressure': 1015, 'humidity':...",NaN,Keelung,NaN,NaN,"{'type': 1, 'id': 7949, 'message': 0.0053, 'co...",8000.0,"[{'id': 803, 'main': 'Clouds', 'description': ...","{'speed': 2.6, 'deg': 280}"
616,stations,{'all': 40},200,"{'lon': -82.29, 'lat': 22.72}",1.552909e+09,3567655.0,"{'temp': 293.93, 'pressure': 1015, 'humidity':...",NaN,Batabano,NaN,NaN,"{'type': 1, 'id': 7236, 'message': 0.0036, 'co...",9000.0,"[{'id': 802, 'main': 'Clouds', 'description': ...","{'speed': 1.5, 'deg': 70}"
617,stations,{'all': 0},200,"{'lon': -67.43, 'lat': 8.92}",1.552910e+09,3647444.0,"{'temp': 299.565, 'pressure': 1012.71, 'humidi...",NaN,Calabozo,NaN,NaN,"{'message': 0.0052, 'country': 'VE', 'sunrise'...",NaN,"[{'id': 800, 'main': 'Clear', 'description': '...","{'speed': 6.92, 'deg': 69.001}"
618,stations,{'all': 0},200,"{'lon': -60.15, 'lat': -12.74}",1.552907e+09,3924679.0,"{'temp': 295.15, 'pressure': 1015, 'humidity':...",NaN,Vilhena,NaN,NaN,"{'type': 1, 'id': 8457, 'message': 0.0032, 'co...",10000.0,"[{'id': 800, 'main': 'Clear', 'description': '...",{'speed': 1}
619,stations,{'all': 44},200,"{'lon': -67.92, 'lat': -17.23}",1.552910e+09,3908339.0,"{'temp': 274.365, 'pressure': 1012.59, 'humidi...",NaN,Patacamaya,{'3h': 0.12},NaN,"{'message': 0.0039, 'country': 'BO', 'sunrise'...",NaN,"[{'id': 500, 'main': 'Rain', 'description': 'l...","{'speed': 1.72, 'deg': 341.501}"
620,stations,{'all': 8},200,"{'lon': 49.05, 'lat': -13.19}",1.552910e+09,1082243.0,"{'temp': 302.515, 'pressure': 1009.99, 'humidi...",NaN,Ambilobe,{'3h': 0.31},NaN,"{'message': 0.0033, 'country': 'MG', 'sunrise'...",NaN,"[{'id': 500, 'main': 'Rain', 'description': 'l...","{'speed': 2.07, 'deg': 261.501}"
621,stations,{'all': 76},200,"{'lon': 109.03, 'lat': 53.41}",1.552910e+09,2013986.0,"{'temp': 269.215, 'pressure': 1011.23, 'humidi...",NaN,Ust-Barguzin,NaN,NaN,"{'message': 0.0041, 'country': 'RU', 'sunrise'...",NaN,"[{'id': 803, 'main': 'Clouds', 'description': ...","{'speed': 4.07, 'deg': 342.001}"
622,stations,{'all': 0},200,"{'lon': -39.21, 'lat': -10.75}",1.552910e+09,3452029.0,"{'temp': 303.165, 'pressure': 1013.31, 'humidi...",NaN,Quijingue,NaN,NaN,"{'message': 0.0034, 'country': 'BR', 'sunrise'...",NaN,"[{'id': 800, 'main': 'Clear', 'description': '...","{'speed': 3.47, 'deg': 62.501}"
623,stations,{'all': 0},200,"{'lon': -9.58, 'lat': 30.42}",1.552907e+09,2561668.0,"{'temp': 292.15, 'pressure': 1018, 'humidity':...",NaN,Agadir,NaN,NaN,"{'type': 1, 'id': 2393, 'message': 0.0039, 'co...",10000.0,"[{'id': 800, 'main': 'Clear', 'description': '...","{'speed': 1.5, 'deg': 130}"
624,stations,{'all': 90},200,"{'lon': 3.91, 'lat': 46.42}",1.552910e+09,2980080.0,"{'temp': 279.96, 'pressure': 1023, 'humidity':...",NaN,Saint-Francois,NaN,NaN,"{'type': 1, 'id': 6499, 'message': 0.0045, 'co...",10000.0,"[{'id': 804, 'main': 'Clouds', 'description': ...","{'speed': 3.6, 'deg': 320}"
625,stations,{'all': 76},200,"{'lon': 104.19, 'lat': -3.5}",1.552910e+09,1631393.0,"{'temp': 296.765, 'pressure': 1010.43, 'humidi...",NaN,Prabumulih,{'3h': 8.795},NaN,"{'message': 0.0037, 'country': 'ID', 'sunrise'...",NaN,"[{'id': 501, 'main': 'Rain', 'description': 'm...","{'speed': 1.24, 'deg': 93.001}"
626,stations,{'all': 36},200,"{'lon': 150.89, 'lat': 65.73}",1.552910e+09,2119283.0,"{'temp': 248.315, 'pressure': 1022.27, 'humidi...",NaN,Zyryanka,NaN,NaN,"{'message': 0.0041, 'country': 'RU', 'sunrise'...",NaN,"[{'id': 802, 'main': 'Clouds', 'description': ...","{'speed': 2.52, 'deg': 336.001}"
627,NaN,NaN,404,NaN,NaN,NaN,NaN,city not found,NaN,NaN,NaN,NaN,NaN,NaN,NaN
628,NaN,NaN,404,NaN,NaN,NaN,NaN,city not found,NaN,NaN,NaN,NaN,NaN,NaN,NaN
629,NaN,NaN,404,NaN,NaN,NaN,NaN,city not found,NaN,NaN,NaN,NaN,NaN,NaN,NaN
630,stations,{'all': 68},200,"{'lon': 94.8, 'lat': 28.17}",1.552910e+09,1278969.0,"{'temp': 285.515, 'pressure': 1012.91, 'humidi...",NaN,Along,{'3h': 1.485},NaN,"{'message': 0.003, 'country': 'IN', 'sunrise':...",NaN,"[{'id': 500, 'main': 'Rain', 'description': 'l...","{'speed': 0.84, 'deg': 340.001}"
631,stations,{'all': 20},200,"{'lon': 33.93, 'lat': -9.94}",1.552910e+09,235715.0,"{'temp': 303.665, 'pressure': 1006.35, 'humidi...",NaN,Karonga,NaN,NaN,"{'message': 0.0065, 'country': 'MW', 'sunrise'...",NaN,"[{'id': 801, 'main': 'Clouds', 'description': ...","{'speed': 1.44, 'deg': 126.001}"
632,stations,{'all': 0},200,"{'lon': 116.85, 'lat': -20.74}",1.552910e+09,6620339.0,"{'temp': 302.315, 'pressure': 1008.43, 'humidi...",NaN,Karratha,{'3h': 0.4325},NaN,"{'message': 0.0032, 'country': 'AU', 'sunrise'...",NaN,"[{'id': 500, 'main': 'Rain', 'description': 'l...","{'speed': 0.89, 'deg': 209.501}"
633,stations,{'all': 40},200,"{'lon': -134.42, 'lat': 58.3}",1.552909e+09,5554072.0,"{'temp': 282.57, 'pressure': 1018, 'humidity':...",NaN,Juneau,NaN,NaN,"{'type': 1, 'id': 7729, 'message': 0.0044, 'co...",16093.0,"[{'id': 802, 'main': 'Clouds', 'description': ...","{'speed': 8.7, 'deg': 110}"